DROP DATABASE IF EXISTS Registration;
CREATE DATABASE Registration;
USE Registration;

CREATE TABLE Student (
    StudentID INT AUTO_INCREMENT PRIMARY KEY,
    Name TINYTEXT,
    Email TINYTEXT,
    age INT,
    DateOfBirth DATE
) Engine=InnoDB;

Create TABLE Course (
    CourseID INT AUTO_INCREMENT PRIMARY KEY,
    ShortName TINYTEXT,
    LongName TINYTEXT
) Engine=InnoDB;

-- DROP TABLE section;
CREATE TABLE Section (
    SectionID INT AUTO_INCREMENT PRIMARY KEY,
    Semester VARCHAR(3),
    InstructorName TINYTEXT,
    CourseID INT NOT NULL,
    FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE ON UPDATE CASCADE
 ) Engine=InnoDB;

CREATE TABLE Enrollment (
    EnrollmentID INT AUTO_INCREMENT PRIMARY KEY,
    StudentID INT NOT NULL,
    SectionID INT NOT NULL,
    Outcome VARCHAR(2),
    FOREIGN KEY (SectionID) REFERENCES Section (SectionID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (StudentID) REFERENCES Student (StudentID) ON DELETE CASCADE ON UPDATE CASCADE
) Engine=InnoDB;


-- Insert Students
insert into student (name, email, age, DateOfBirth) values ('Truman Aynscombe', 'taynscombe0@jigsy.com', 30, '1986-05-04 02:46:18');
insert into student (name, email, age, DateOfBirth) values ('Joelynn Pottle', 'jpottle1@ed.gov', 59, '1968-01-07 15:47:10');
insert into student (name, email, age, DateOfBirth) values ('Truman Steptowe', 'tsteptowe2@mashable.com', 79, '1978-11-24 13:27:27');
insert into student (name, email, age, DateOfBirth) values ('Avery Olivi', 'aolivi3@fotki.com', 60, '2019-11-24 16:26:30');
insert into student (name, email, age, DateOfBirth) values ('Ethan Riall', 'eriall4@aboutads.info', 66, '2001-12-31 07:37:26');
insert into student (name, email, age, DateOfBirth) values ('Arnold Lennon', 'alennon5@va.gov', 32, '1967-10-27 22:27:57');
insert into student (name, email, age, DateOfBirth) values ('Helaine Sandom', 'hsandom6@ftc.gov', 49, '1976-11-06 20:47:12');
insert into student (name, email, age, DateOfBirth) values ('Etienne Nichol', 'enichol7@google.es', 19, '2002-11-15 15:37:50');
insert into student (name, email, age, DateOfBirth) values ('Eunice Velten', 'evelten8@si.edu', 49, '2019-11-03 13:37:00');
insert into student (name, email, age, DateOfBirth) values ('Dell Pardue', 'dpardue9@diigo.com', 63, '2001-03-25 11:30:36');
insert into student (name, email, age, DateOfBirth) values ('Arnie Aleksahkin', 'aaleksahkina@weebly.com', 21, '1949-06-15 01:22:40');
insert into student (name, email, age, DateOfBirth) values ('Riki Danhel', 'rdanhelb@wiley.com', 55, '1957-10-25 18:15:04');
insert into student (name, email, age, DateOfBirth) values ('Viola Worgen', 'vworgenc@uol.com.br', 46, '1928-03-12 14:06:24');
insert into student (name, email, age, DateOfBirth) values ('Mirabel Rose', 'mrosed@huffingtonpost.com', 40, '1995-04-12 09:46:31');
insert into student (name, email, age, DateOfBirth) values ('Danella Kubera', 'dkuberae@nps.gov', 94, '1977-11-13 00:01:14');
insert into student (name, email, age, DateOfBirth) values ('Caro Mompesson', 'cmompessonf@bing.com', 83, '1997-07-30 03:51:28');
insert into student (name, email, age, DateOfBirth) values ('Nanny Mercy', 'nmercyg@technorati.com', 70, '1966-05-09 20:07:21');
insert into student (name, email, age, DateOfBirth) values ('Thelma Tarney', 'ttarneyh@lulu.com', 26, '1996-06-12 13:51:40');
insert into student (name, email, age, DateOfBirth) values ('Alano Upwood', 'aupwoodi@edublogs.org', 35, '1942-08-17 22:50:01');
insert into student (name, email, age, DateOfBirth) values ('Sindee Iuorio', 'siuorioj@miitbeian.gov.cn', 29, '2008-01-30 00:45:10');
insert into student (name, email, age, DateOfBirth) values ('Clyde Wildt', 'cwildtk@tiny.cc', 40, '1978-05-07 00:19:06');
insert into student (name, email, age, DateOfBirth) values ('Leola Andrasch', 'landraschl@bigcartel.com', 92, '1988-02-28 14:01:57');
insert into student (name, email, age, DateOfBirth) values ('Shellysheldon Tatterton', 'stattertonm@issuu.com', 87, '1932-12-23 04:58:31');
insert into student (name, email, age, DateOfBirth) values ('Terrell Newport', 'tnewportn@joomla.org', 61, '1971-10-03 17:46:46');
insert into student (name, email, age, DateOfBirth) values ('Orv Carlan', 'ocarlano@technorati.com', 94, '1980-05-21 19:53:28');
insert into student (name, email, age, DateOfBirth) values ('Melissa Fazackerley', 'mfazackerleyp@archive.org', 36, '1996-10-13 11:51:46');
insert into student (name, email, age, DateOfBirth) values ('Kristopher Boniface', 'kbonifaceq@webnode.com', 62, '1999-01-17 02:47:17');
insert into student (name, email, age, DateOfBirth) values ('Giles Leyband', 'gleybandr@abc.net.au', 73, '1998-02-08 03:52:26');
insert into student (name, email, age, DateOfBirth) values ('Anabelle Corbie', 'acorbies@linkedin.com', 41, '1982-04-13 09:54:21');
insert into student (name, email, age, DateOfBirth) values ('Ewan Worthing', 'eworthingt@mozilla.org', 36, '1974-01-04 07:16:42');
insert into student (name, email, age, DateOfBirth) values ('Cami Goldson', 'cgoldsonu@mail.ru', 31, '2004-01-05 07:20:20');
insert into student (name, email, age, DateOfBirth) values ('Angelina Deftie', 'adeftiev@people.com.cn', 47, '1964-01-09 12:19:38');
insert into student (name, email, age, DateOfBirth) values ('Mal Mayhow', 'mmayhoww@sphinn.com', 49, '1940-06-24 17:03:10');
insert into student (name, email, age, DateOfBirth) values ('Desmund Cluer', 'dcluerx@tripadvisor.com', 94, '1993-11-02 01:56:17');
insert into student (name, email, age, DateOfBirth) values ('Merell Kleinlerer', 'mkleinlerery@soundcloud.com', 95, '1972-10-06 06:04:34');
insert into student (name, email, age, DateOfBirth) values ('Horton Burdoun', 'hburdounz@desdev.cn', 94, '1937-01-05 01:47:55');
insert into student (name, email, age, DateOfBirth) values ('Fred Mell', 'fmell10@ucoz.com', 67, '2005-03-20 17:51:11');
insert into student (name, email, age, DateOfBirth) values ('Carlie Logg', 'clogg11@dailymail.co.uk', 53, '1955-01-05 10:51:14');
insert into student (name, email, age, DateOfBirth) values ('Beulah Davidsen', 'bdavidsen12@blogs.com', 57, '1950-09-11 06:52:56');
insert into student (name, email, age, DateOfBirth) values ('Virginie Jentzsch', 'vjentzsch13@360.cn', 27, '1998-08-10 16:01:57');
insert into student (name, email, age, DateOfBirth) values ('Garry Cogzell', 'gcogzell14@mozilla.org', 24, '1958-06-16 11:13:13');
insert into student (name, email, age, DateOfBirth) values ('Devin Keymar', 'dkeymar15@netvibes.com', 64, '1963-02-27 03:01:46');
insert into student (name, email, age, DateOfBirth) values ('Fanchon Satterfitt', 'fsatterfitt16@whitehouse.gov', 93, '1936-04-19 09:50:26');
insert into student (name, email, age, DateOfBirth) values ('Thomasa Olek', 'tolek17@webnode.com', 70, '1930-11-30 22:51:47');
insert into student (name, email, age, DateOfBirth) values ('Onida Gotcher', 'ogotcher18@quantcast.com', 93, '2009-11-05 19:49:21');
insert into student (name, email, age, DateOfBirth) values ('Desirae Pohling', 'dpohling19@ow.ly', 32, '1966-05-20 09:56:55');
insert into student (name, email, age, DateOfBirth) values ('Joseito Rubke', 'jrubke1a@cyberchimps.com', 41, '2003-07-22 20:20:51');
insert into student (name, email, age, DateOfBirth) values ('Zorana Bembrick', 'zbembrick1b@apache.org', 77, '1997-12-05 18:52:50');
insert into student (name, email, age, DateOfBirth) values ('Helsa Barz', 'hbarz1c@cisco.com', 90, '1966-02-25 23:10:04');
insert into student (name, email, age, DateOfBirth) values ('Eden Ruthven', 'eruthven1d@twitter.com', 45, '1959-01-22 01:38:14');
insert into student (name, email, age, DateOfBirth) values ('Marrissa Lemasney', 'mlemasney1e@youku.com', 85, '1944-03-16 01:22:46');
insert into student (name, email, age, DateOfBirth) values ('Marya Drexel', 'mdrexel1f@scientificamerican.com', 94, '2014-12-25 04:10:35');
insert into student (name, email, age, DateOfBirth) values ('Fernanda Easseby', 'feasseby1g@businesswire.com', 71, '1987-03-15 10:41:54');
insert into student (name, email, age, DateOfBirth) values ('George Davis', 'gdavis1h@etsy.com', 48, '1958-12-10 11:08:37');
insert into student (name, email, age, DateOfBirth) values ('Augy Gasperi', 'agasperi1i@infoseek.co.jp', 43, '1920-12-10 04:16:55');
insert into student (name, email, age, DateOfBirth) values ('Verna Domsalla', 'vdomsalla1j@e-recht24.de', 20, '1920-12-22 13:37:18');
insert into student (name, email, age, DateOfBirth) values ('Hedvige McWhannel', 'hmcwhannel1k@ycombinator.com', 91, '1972-07-10 19:50:30');
insert into student (name, email, age, DateOfBirth) values ('Inga Caught', 'icaught1l@businessweek.com', 67, '2004-08-02 15:25:42');
insert into student (name, email, age, DateOfBirth) values ('Julian McLachlan', 'jmclachlan1m@virginia.edu', 20, '1953-01-24 10:56:55');
insert into student (name, email, age, DateOfBirth) values ('Murdoch Barcke', 'mbarcke1n@illinois.edu', 33, '2015-06-15 04:53:21');
insert into student (name, email, age, DateOfBirth) values ('Verla Goodsal', 'vgoodsal1o@blogger.com', 30, '1938-08-29 15:39:55');
insert into student (name, email, age, DateOfBirth) values ('Sadie Kilbane', 'skilbane1p@washingtonpost.com', 88, '1972-04-18 00:35:57');
insert into student (name, email, age, DateOfBirth) values ('Nicoli Kardos', 'nkardos1q@gmpg.org', 93, '2003-01-04 15:50:14');
insert into student (name, email, age, DateOfBirth) values ('Helaine Booth-Jarvis', 'hboothjarvis1r@youtube.com', 81, '1956-06-12 06:57:43');
insert into student (name, email, age, DateOfBirth) values ('Drona McDougall', 'dmcdougall1s@photobucket.com', 26, '1958-02-03 22:04:47');
insert into student (name, email, age, DateOfBirth) values ('Brenna Edgell', 'bedgell1t@va.gov', 18, '1961-07-20 04:55:19');
insert into student (name, email, age, DateOfBirth) values ('Carlynn Blackmore', 'cblackmore1u@google.it', 23, '1969-03-06 22:14:41');
insert into student (name, email, age, DateOfBirth) values ('Horatio Maude', 'hmaude1v@cisco.com', 25, '1942-07-12 22:46:11');
insert into student (name, email, age, DateOfBirth) values ('Ulrikaumeko Dickins', 'udickins1w@harvard.edu', 30, '1943-08-24 04:51:27');
insert into student (name, email, age, DateOfBirth) values ('Kaile Gwinnell', 'kgwinnell1x@cmu.edu', 67, '2001-06-19 18:36:01');
insert into student (name, email, age, DateOfBirth) values ('Dorian Portam', 'dportam1y@seesaa.net', 64, '1942-06-17 01:37:27');
insert into student (name, email, age, DateOfBirth) values ('Chrisy Willmett', 'cwillmett1z@friendfeed.com', 81, '1935-02-13 15:28:41');
insert into student (name, email, age, DateOfBirth) values ('Kenton Geertz', 'kgeertz20@abc.net.au', 62, '1970-02-23 04:38:27');
insert into student (name, email, age, DateOfBirth) values ('Peter Jordine', 'pjordine21@wsj.com', 81, '1977-07-03 22:19:11');
insert into student (name, email, age, DateOfBirth) values ('Gennifer Elverstone', 'gelverstone22@exblog.jp', 29, '1985-08-24 05:19:23');
insert into student (name, email, age, DateOfBirth) values ('Norah Braddock', 'nbraddock23@reverbnation.com', 85, '1965-04-09 02:45:02');
insert into student (name, email, age, DateOfBirth) values ('Reinold Branch', 'rbranch24@geocities.jp', 28, '1923-07-08 00:41:28');
insert into student (name, email, age, DateOfBirth) values ('Stacee Cavan', 'scavan25@instagram.com', 71, '1978-10-03 05:13:53');
insert into student (name, email, age, DateOfBirth) values ('Pepito Marshallsay', 'pmarshallsay26@feedburner.com', 88, '1925-02-26 02:36:54');
insert into student (name, email, age, DateOfBirth) values ('Miller Papaminas', 'mpapaminas27@globo.com', 55, '1947-04-19 13:52:14');
insert into student (name, email, age, DateOfBirth) values ('Nixie Ratcliffe', 'nratcliffe28@free.fr', 89, '1969-10-16 18:53:09');
insert into student (name, email, age, DateOfBirth) values ('Roderigo Straine', 'rstraine29@photobucket.com', 28, '1976-01-06 17:16:49');
insert into student (name, email, age, DateOfBirth) values ('Eve Daborn', 'edaborn2a@oracle.com', 31, '1985-05-07 15:22:34');
insert into student (name, email, age, DateOfBirth) values ('Ashlin Artinstall', 'aartinstall2b@e-recht24.de', 52, '1930-08-13 15:02:34');
insert into student (name, email, age, DateOfBirth) values ('Myrilla Heasman', 'mheasman2c@youku.com', 67, '1945-03-02 11:55:42');
insert into student (name, email, age, DateOfBirth) values ('Augie Carnilian', 'acarnilian2d@engadget.com', 20, '1930-01-23 09:33:11');
insert into student (name, email, age, DateOfBirth) values ('Nonie Gavan', 'ngavan2e@noaa.gov', 92, '1997-03-02 21:50:14');
insert into student (name, email, age, DateOfBirth) values ('Henrieta Van Bruggen', 'hvan2f@mysql.com', 28, '1995-02-04 19:47:17');
insert into student (name, email, age, DateOfBirth) values ('Lanae Iddenden', 'liddenden2g@wisc.edu', 62, '2001-12-18 02:58:57');
insert into student (name, email, age, DateOfBirth) values ('Cari Hallum', 'challum2h@cafepress.com', 22, '1977-10-26 09:42:11');
insert into student (name, email, age, DateOfBirth) values ('Letti Banisch', 'lbanisch2i@mayoclinic.com', 55, '1945-08-08 22:35:41');
insert into student (name, email, age, DateOfBirth) values ('Royall Hyrons', 'rhyrons2j@posterous.com', 18, '1980-02-25 06:19:16');
insert into student (name, email, age, DateOfBirth) values ('Hannis Woodroffe', 'hwoodroffe2k@amazon.com', 76, '1956-04-23 03:52:22');
insert into student (name, email, age, DateOfBirth) values ('Aindrea Lampens', 'alampens2l@paypal.com', 86, '1955-06-04 19:51:20');
insert into student (name, email, age, DateOfBirth) values ('Roderic Regler', 'rregler2m@vimeo.com', 36, '1944-03-16 08:16:51');
insert into student (name, email, age, DateOfBirth) values ('Pia Knath', 'pknath2n@seesaa.net', 97, '1926-10-15 15:28:44');
insert into student (name, email, age, DateOfBirth) values ('Jay Drinan', 'jdrinan2o@java.com', 18, '1970-04-03 17:46:51');
insert into student (name, email, age, DateOfBirth) values ('Reggis Mulles', 'rmulles2p@t.co', 74, '1959-03-01 11:56:43');
insert into student (name, email, age, DateOfBirth) values ('Sax Proughten', 'sproughten2q@exblog.jp', 100, '1940-10-20 14:53:30');
insert into student (name, email, age, DateOfBirth) values ('Talbert Giffon', 'tgiffon2r@goodreads.com', 65, '2013-03-19 05:16:25');

SELECT * FROM Student;

-- Insert Courses
INSERT INTO Course (ShortName, LongName) 
    VALUES ('CSIS 3275', 'Software Engineering'),
    ('CSIS 3380', 'Full Stack Development with Javascript'),
    ('CSIS 3280', 'Web Development with PHP'),
    ('CSIS 1280', 'Front End Web Development with HTML/CSS and Javascript'),
    ('CSIS 3540', 'Client Server Systems'),
    ('CSIS 2175', 'Advanced Integrated Programming with Java'),
    ('CSIS 1190', 'Excel'),
    ('CSIS 2200', 'Systems Analysis and Design'),
    ('CSIS 2260', 'Operating Systems');

SELECT * FROM Course;

-- Insert Sections

insert into section (Semester, InstructorName, CourseID) values ('S19', 'Michael Wufka', 1);
insert into section (Semester, InstructorName, CourseID) values ('S19', 'Simon Li', 9);
insert into section (Semester, InstructorName, CourseID) values ('W20', 'Michael Ma', 2);
insert into section (Semester, InstructorName, CourseID) values ('F21', 'Stephen Choing', 8);
insert into section (Semester, InstructorName, CourseID) values ('F20', 'Mehwish Bashir', 6);
insert into section (Semester, InstructorName, CourseID) values ('F21', 'Priya Khadnarai', 7);
insert into section (Semester, InstructorName, CourseID) values ('S20', 'Mehwish Bashir', 8);
insert into section (Semester, InstructorName, CourseID) values ('W19', 'Michael Ma', 2);
insert into section (Semester, InstructorName, CourseID) values ('W20', 'Rahim Virani', 5);
insert into section (Semester, InstructorName, CourseID) values ('W19', 'Mehwish Bashir', 8);
insert into section (Semester, InstructorName, CourseID) values ('W21', 'Bambang Sarif', 2);
insert into section (Semester, InstructorName, CourseID) values ('S20', 'Michael Ma', 5);
insert into section (Semester, InstructorName, CourseID) values ('F19', 'Mike Hrybk', 1);
insert into section (Semester, InstructorName, CourseID) values ('S19', 'Bambang Sarif', 4);
insert into section (Semester, InstructorName, CourseID) values ('F21', 'Bambang Sarif', 3);
insert into section (Semester, InstructorName, CourseID) values ('S21', 'Mehwish Bashir', 8);
insert into section (Semester, InstructorName, CourseID) values ('S20', 'Bambang Sarif', 8);
insert into section (Semester, InstructorName, CourseID) values ('W20', 'Stephen Choing', 5);
insert into section (Semester, InstructorName, CourseID) values ('S20', 'Stephen Choing', 2);
insert into section (Semester, InstructorName, CourseID) values ('F21', 'Mike Hrybk', 9);
insert into section (Semester, InstructorName, CourseID) values ('F21', 'Mehwish Bashir', 4);
insert into section (Semester, InstructorName, CourseID) values ('S21', 'Michael Wufka', 3);
insert into section (Semester, InstructorName, CourseID) values ('F19', 'Rahim Virani', 7);


SELECT COUNT(*) FROM Student; -- 100
SELECT COUNT(*) FROM Course; -- 9 
SELECT COUNT(*) FROM section; -- 23

DESC enrollment;

-- enrollments

insert into enrollment (StudentID, SectionID, Outcome) values (82, 21, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 8, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (46, 15, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 7, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (36, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 11, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (96, 9, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 12, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (94, 6, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 7, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (72, 18, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 6, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (43, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 5, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 3, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 20, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (82, 19, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 16, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 2, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (48, 17, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (22, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (85, 20, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (98, 16, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (92, 18, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 16, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (91, 2, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 3, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (86, 21, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 10, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (22, 3, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 19, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (47, 13, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 11, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 15, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 11, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 19, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 3, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (11, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (43, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (5, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (4, 14, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (87, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 2, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (13, 23, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (80, 18, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 23, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 16, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 21, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (9, 2, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (83, 10, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (60, 12, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (88, 22, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 10, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 4, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (41, 2, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 18, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 13, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (100, 15, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 12, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (10, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 12, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 6, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (74, 11, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 8, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (24, 22, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 12, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (56, 22, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 5, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (66, 17, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 4, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (13, 15, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (12, 22, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (40, 23, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (80, 20, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (72, 5, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 17, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 16, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (37, 11, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (64, 21, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (66, 8, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 21, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (29, 16, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (83, 12, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 11, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (44, 7, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (2, 8, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 4, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 19, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (64, 6, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 7, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 10, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 11, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 1, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 14, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (20, 4, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (20, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (10, 15, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (52, 2, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (11, 19, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (98, 12, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (98, 22, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 17, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (37, 2, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 8, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (13, 11, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 2, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (62, 13, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 8, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 18, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 4, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 11, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (81, 21, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (38, 4, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 3, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (82, 12, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 4, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (48, 18, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (50, 16, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 8, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 23, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 17, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (78, 18, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (41, 14, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 9, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (8, 12, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 5, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (43, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 7, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (22, 4, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 15, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 6, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 9, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (85, 14, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 2, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 10, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 2, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 19, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 2, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (56, 13, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (19, 10, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 21, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (50, 1, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 13, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 12, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (6, 4, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (52, 22, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 12, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 9, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 16, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 13, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 10, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 5, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 9, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 18, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (85, 21, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 11, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 21, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (86, 12, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 11, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (74, 6, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 1, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 17, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 10, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 18, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 21, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (41, 2, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 17, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (65, 14, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 4, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 14, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (10, 14, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (86, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (20, 18, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (62, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 12, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 9, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 3, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 12, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 8, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (60, 18, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 11, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (23, 7, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (4, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (61, 17, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 7, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 10, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (36, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (64, 21, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (62, 2, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (74, 16, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (41, 22, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (59, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (5, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 8, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (12, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (59, 21, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (36, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (74, 6, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (43, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 2, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (70, 7, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (27, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 14, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 23, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (12, 7, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 15, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 7, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 4, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (66, 16, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 23, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 8, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (38, 4, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (56, 18, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 13, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (59, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (81, 10, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (52, 4, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 16, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 6, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (9, 20, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 8, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 10, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 12, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 19, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (89, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 5, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 17, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 17, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 3, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (50, 20, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (44, 17, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 14, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (9, 18, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 6, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 22, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 14, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (12, 1, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (65, 6, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 8, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 22, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 21, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (38, 19, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (37, 15, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 5, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (83, 3, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 22, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (100, 21, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (21, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 12, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (64, 10, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 4, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (23, 1, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (100, 1, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (91, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (47, 23, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 7, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 9, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (63, 8, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (6, 11, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (40, 19, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 14, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 21, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (64, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (91, 11, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (40, 17, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 22, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (12, 13, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (60, 2, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 23, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (83, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 19, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 7, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 5, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 7, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (78, 21, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 8, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (88, 7, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (80, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (73, 2, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (63, 15, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (20, 13, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 14, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 8, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 7, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (85, 8, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 13, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 10, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (73, 9, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (100, 22, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (100, 10, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (46, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (29, 11, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (11, 13, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 5, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 3, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (5, 19, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 8, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 2, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (5, 2, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (38, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 18, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 9, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 2, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 9, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (94, 5, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (10, 1, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (24, 4, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (2, 18, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 18, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 9, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (13, 22, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 10, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 15, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 12, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (65, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (87, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (59, 2, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 21, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (27, 2, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (98, 14, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 12, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (44, 8, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (89, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (21, 6, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (19, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 1, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 8, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (72, 23, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 17, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (8, 20, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 20, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 19, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (98, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 11, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 21, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (89, 22, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 6, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (91, 8, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (73, 9, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (82, 12, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 9, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (87, 5, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (86, 20, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 18, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (44, 10, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 9, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 15, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 4, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 15, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 4, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 4, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (27, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 5, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (59, 1, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 2, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 20, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 20, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 19, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 14, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 3, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 19, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 5, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (45, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (74, 13, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 20, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (75, 21, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 4, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 6, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 1, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 3, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (43, 4, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (59, 20, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (9, 1, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 19, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 14, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 18, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 13, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 7, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (88, 21, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 20, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (46, 19, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (92, 5, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (37, 7, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (48, 5, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (85, 10, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (28, 18, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (66, 1, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (56, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (62, 13, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (82, 4, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (47, 23, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (52, 15, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 16, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (40, 12, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 3, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (10, 10, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 18, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (37, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 14, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 11, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 9, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 20, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (66, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (22, 1, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (78, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (19, 15, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 13, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 2, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (90, 11, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (52, 17, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (86, 18, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 16, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 3, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (91, 13, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (52, 17, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (62, 3, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 7, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (4, 10, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (82, 20, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (10, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (58, 23, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 13, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (30, 12, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (89, 10, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (83, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 21, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 11, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 2, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (56, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 4, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 19, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (9, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (14, 1, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (13, 19, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 19, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 4, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (75, 7, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (65, 20, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (69, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 13, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 23, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (16, 13, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 6, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 2, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (27, 10, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (11, 6, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 22, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 17, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 11, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (15, 21, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 3, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 1, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (78, 22, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (75, 10, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 23, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (7, 13, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (49, 9, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (62, 23, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 22, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (42, 12, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (66, 20, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (41, 2, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (25, 14, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (89, 11, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (47, 19, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (78, 17, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 5, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (13, 21, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 16, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (46, 18, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 23, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 11, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (94, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (19, 4, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 9, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (51, 15, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (84, 19, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (2, 4, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (36, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (11, 15, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (76, 22, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (82, 14, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (18, 16, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (53, 12, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (89, 8, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (72, 15, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (75, 18, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (1, 1, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 11, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (33, 9, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 7, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (32, 20, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (5, 10, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (88, 13, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (93, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (31, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (3, 14, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (83, 17, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 15, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 1, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (5, 7, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (12, 6, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (57, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (23, 14, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 14, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (68, 19, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (75, 10, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (55, 1, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (99, 18, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (39, 8, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (9, 14, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (77, 9, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (54, 4, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (8, 22, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (20, 21, 'F');
insert into enrollment (StudentID, SectionID, Outcome) values (85, 6, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (97, 16, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (35, 8, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (34, 9, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (24, 16, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (67, 8, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (36, 17, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (21, 1, 'E');
insert into enrollment (StudentID, SectionID, Outcome) values (20, 2, 'P');
insert into enrollment (StudentID, SectionID, Outcome) values (17, 15, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (2, 16, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (26, 11, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (29, 13, 'C');
insert into enrollment (StudentID, SectionID, Outcome) values (24, 15, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (37, 1, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (91, 7, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (95, 20, 'UN');
insert into enrollment (StudentID, SectionID, Outcome) values (78, 21, 'B');
insert into enrollment (StudentID, SectionID, Outcome) values (73, 7, 'A');
insert into enrollment (StudentID, SectionID, Outcome) values (79, 7, 'UN');
